### ISSUE TITLE
Problem with encapsulation

### ISSUE THREAD

**Issue by jscissr** [webcomponents/shadycss#104] opened 2017-06-07 18:18 UTC
Demo: http://jsbin.com/fijopuqeva/edit?html,output

I found that `paper-item` Polymer elements which are dynamically inserted into the DOM are missing some styles (padding and min-height), but *only* if there is a `paper-swatch-picker` Polymer element anywhere in the DOM. You can try it out; if you remove `paper-swatch-picker` the problem is gone.

This is clearly a bug, the styling of some elements should not be affected by the presence of other unrelated elements in the DOM. And it seems that the bug is caused by a limitation in ApplyShim of shadycss, see https://github.com/webcomponents/shadycss/blob/05a16c279897fa6d520169a0fad3975fa75ea690/src/apply-shim.js#L57

I don't know whether the bug can be fixed here, or needs a workaround in `paper-item` or `paper-swatch-picker`.

**Comment by azakus** [comment] 2017-09-22 23:44
Hmm, I redid your example with the released versions of polymer, webcomponents, and shadycss and I can't reproduce: http://jsbin.com/kiqigo/2/edit?html,output

Seems like this might be fixed now. If this is still a problem, please reopen!

**Closed by azakus** 2017-09-22 23:44 UTC
