### ISSUE TITLE
Object.assign not supported in IE11

### ISSUE THREAD

**Issue by valdrinkoshi** [webcomponents/shadycss#35] opened 2016-12-07 20:05 UTC
`Object.assign` is not supported in IE11 http://kangax.github.io/compat-table/es6/#test-Object_static_methods_Object.assign

Used in
https://github.com/webcomponents/shadycss/blob/master/src/style-properties.js#L73
https://github.com/webcomponents/shadycss/blob/master/src/ShadyCSS.js#L237
https://github.com/webcomponents/shadycss/blob/master/src/ShadyCSS.js#L156

@azakus FYI

**Comment by Hotell** [comment] 2016-12-08 08:39
duplicate of #29

**Comment by azakus** [comment] 2016-12-21 19:50
Closing as dupe

**Closed by azakus** 2016-12-21 19:50 UTC
